// <auto-generated />
using System;
using DailyPlanner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DailyPlanner.Migrations
{
    [DbContext(typeof(PlannerDbContext))]
    [Migration("20260306144353_FixIndexesAndMaxLengths")]
    partial class FixIndexesAndMaxLengths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("DailyPlanner.Models.DailyPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("WeekId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WeekId", "Date")
                        .IsUnique();

                    b.ToTable("DailyPlans");
                });

            modelBuilder.Entity("DailyPlanner.Models.DailyState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Energy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mood")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sleep")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DailyPlanId")
                        .IsUnique();

                    b.ToTable("DailyStates");
                });

            modelBuilder.Entity("DailyPlanner.Models.DailyTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly?>("ReminderTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DailyPlanId");

                    b.ToTable("DailyTasks");
                });

            modelBuilder.Entity("DailyPlanner.Models.HabitDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WeekId");

                    b.ToTable("HabitDefinitions");
                });

            modelBuilder.Entity("DailyPlanner.Models.HabitEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HabitDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HabitDefinitionId");

                    b.ToTable("HabitEntries");
                });

            modelBuilder.Entity("DailyPlanner.Models.PlannerWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartDate")
                        .IsUnique();

                    b.ToTable("Weeks");
                });

            modelBuilder.Entity("DailyPlanner.Models.RecurringTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RecurringTemplates");
                });

            modelBuilder.Entity("DailyPlanner.Models.WeeklyGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("WeekId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WeekId");

                    b.ToTable("WeeklyGoals");
                });

            modelBuilder.Entity("DailyPlanner.Models.DailyPlan", b =>
                {
                    b.HasOne("DailyPlanner.Models.PlannerWeek", "Week")
                        .WithMany("Days")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Week");
                });

            modelBuilder.Entity("DailyPlanner.Models.DailyState", b =>
                {
                    b.HasOne("DailyPlanner.Models.DailyPlan", "DailyPlan")
                        .WithOne("State")
                        .HasForeignKey("DailyPlanner.Models.DailyState", "DailyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyPlan");
                });

            modelBuilder.Entity("DailyPlanner.Models.DailyTask", b =>
                {
                    b.HasOne("DailyPlanner.Models.DailyPlan", "DailyPlan")
                        .WithMany("Tasks")
                        .HasForeignKey("DailyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyPlan");
                });

            modelBuilder.Entity("DailyPlanner.Models.HabitDefinition", b =>
                {
                    b.HasOne("DailyPlanner.Models.PlannerWeek", "Week")
                        .WithMany("Habits")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Week");
                });

            modelBuilder.Entity("DailyPlanner.Models.HabitEntry", b =>
                {
                    b.HasOne("DailyPlanner.Models.HabitDefinition", "HabitDefinition")
                        .WithMany("Entries")
                        .HasForeignKey("HabitDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HabitDefinition");
                });

            modelBuilder.Entity("DailyPlanner.Models.WeeklyGoal", b =>
                {
                    b.HasOne("DailyPlanner.Models.PlannerWeek", "Week")
                        .WithMany("Goals")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Week");
                });

            modelBuilder.Entity("DailyPlanner.Models.DailyPlan", b =>
                {
                    b.Navigation("State");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("DailyPlanner.Models.HabitDefinition", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("DailyPlanner.Models.PlannerWeek", b =>
                {
                    b.Navigation("Days");

                    b.Navigation("Goals");

                    b.Navigation("Habits");
                });
#pragma warning restore 612, 618
        }
    }
}
